### PR TITLE
adding books

### PR DESCRIPTION
**Pull request by Wise-mystic**

### CODE REVIEW

**Review by Jhacy456 — APPROVED** [review]
good job

**Comment by Jhacy456** [comment]
good job

**Review by Jhacy456 — APPROVED** [review]
good

**Review by Jhacy456 — APPROVED** [review]

**Review by Jhacy456 — APPROVED** [review]

**Review by Jhacy456 — APPROVED** [review]

**Review by Jhacy456 — APPROVED** [review]
nice

**Review by Jhacy456 — APPROVED** [review]

**Review by Barmoo — APPROVED** [review]
done guys

**Pull request merged**
